# Generated by Django 4.2.16 on 2024-11-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.posts')),
            ],
        ),
    ]
