# Generated by Django 4.2.16 on 2024-11-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_likes_to_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
